"GENERATED"

load("@rules_dotnet//dotnet:defs.bzl", "nuget_repo")

def main():
    "main"
    nuget_repo(
        name = "paket.main",
        packages = [
            {"name": "FSharp.Core", "id": "FSharp.Core", "version": "10.0.100", "sha512": "sha512-AeCswCd28W5ewTOgsg+y9Ri4l6cjwiOKBh7Qb+73Iu8fGRFdmIVU3R/U0Kb3e8yW/Up0Le/4CItCh1GqtXuLRA==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {"net10.0": [], "net11": [], "net20": [], "net30": [], "net35": [], "net40": [], "net403": [], "net45": [], "net451": [], "net452": [], "net46": [], "net461": [], "net462": [], "net47": [], "net471": [], "net472": [], "net48": [], "net5.0": [], "net6.0": [], "net7.0": [], "net8.0": [], "net9.0": [], "netcoreapp1.0": [], "netcoreapp1.1": [], "netcoreapp2.0": [], "netcoreapp2.1": [], "netcoreapp2.2": [], "netcoreapp3.0": [], "netcoreapp3.1": [], "netstandard": [], "netstandard1.0": [], "netstandard1.1": [], "netstandard1.2": [], "netstandard1.3": [], "netstandard1.4": [], "netstandard1.5": [], "netstandard1.6": [], "netstandard2.0": [], "netstandard2.1": []}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "MedallionShell", "id": "MedallionShell", "version": "1.6.2", "sha512": "sha512-o5puRQG92FUjVMm5CLA0jk/SYPPlxCSC1hokT7pvgHdKxYKvcqzkt/9Sug2u/LxYosyLjpD458XxblofuQyaqw==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {"net10.0": [], "net11": [], "net20": [], "net30": [], "net35": [], "net40": [], "net403": [], "net45": [], "net451": [], "net452": [], "net46": [], "net461": [], "net462": [], "net47": [], "net471": [], "net472": [], "net48": [], "net5.0": [], "net6.0": [], "net7.0": [], "net8.0": [], "net9.0": [], "netcoreapp1.0": [], "netcoreapp1.1": [], "netcoreapp2.0": [], "netcoreapp2.1": [], "netcoreapp2.2": [], "netcoreapp3.0": [], "netcoreapp3.1": [], "netstandard": [], "netstandard1.0": [], "netstandard1.1": [], "netstandard1.2": [], "netstandard1.3": [], "netstandard1.4": [], "netstandard1.5": [], "netstandard1.6": [], "netstandard2.0": [], "netstandard2.1": []}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "Microsoft.Bcl.Memory", "id": "Microsoft.Bcl.Memory", "version": "10.0.2", "sha512": "sha512-s3sU96hun2sHg5Up78FaUoHa5zQKjcO3NRyom1iuPtRnZlYx61QF5xZy/uec1qx0phIm86wxx30DxUr0h4vitQ==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {"net10.0": [], "net11": [], "net20": [], "net30": [], "net35": [], "net40": [], "net403": [], "net45": [], "net451": [], "net452": [], "net46": [], "net461": [], "net462": [], "net47": [], "net471": [], "net472": [], "net48": [], "net5.0": [], "net6.0": [], "net7.0": [], "net8.0": [], "net9.0": [], "netcoreapp1.0": [], "netcoreapp1.1": [], "netcoreapp2.0": [], "netcoreapp2.1": [], "netcoreapp2.2": [], "netcoreapp3.0": [], "netcoreapp3.1": [], "netstandard": [], "netstandard1.0": [], "netstandard1.1": [], "netstandard1.2": [], "netstandard1.3": [], "netstandard1.4": [], "netstandard1.5": [], "netstandard1.6": [], "netstandard2.0": [], "netstandard2.1": []}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "TruePath", "id": "TruePath", "version": "1.11.0", "sha512": "sha512-91RZZ0yiPpUbnx52SQ/PWLiBf7wl2UXvUUiCczPXEtGdrrr9qmDrFLX21vHqnxN7YjA9ujA6k/vnNdgxmF1SKw==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {"net10.0": ["Microsoft.Bcl.Memory"], "net11": [], "net20": [], "net30": [], "net35": [], "net40": [], "net403": [], "net45": [], "net451": [], "net452": [], "net46": [], "net461": ["Microsoft.Bcl.Memory"], "net462": ["Microsoft.Bcl.Memory"], "net47": ["Microsoft.Bcl.Memory"], "net471": ["Microsoft.Bcl.Memory"], "net472": ["Microsoft.Bcl.Memory"], "net48": ["Microsoft.Bcl.Memory"], "net5.0": ["Microsoft.Bcl.Memory"], "net6.0": ["Microsoft.Bcl.Memory"], "net7.0": ["Microsoft.Bcl.Memory"], "net8.0": ["Microsoft.Bcl.Memory"], "net9.0": ["Microsoft.Bcl.Memory"], "netcoreapp1.0": [], "netcoreapp1.1": [], "netcoreapp2.0": ["Microsoft.Bcl.Memory"], "netcoreapp2.1": ["Microsoft.Bcl.Memory"], "netcoreapp2.2": ["Microsoft.Bcl.Memory"], "netcoreapp3.0": ["Microsoft.Bcl.Memory"], "netcoreapp3.1": ["Microsoft.Bcl.Memory"], "netstandard": [], "netstandard1.0": [], "netstandard1.1": [], "netstandard1.2": [], "netstandard1.3": [], "netstandard1.4": [], "netstandard1.5": [], "netstandard1.6": [], "netstandard2.0": ["Microsoft.Bcl.Memory"], "netstandard2.1": ["Microsoft.Bcl.Memory"]}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
            {"name": "TruePath.SystemIo", "id": "TruePath.SystemIo", "version": "1.11.0", "sha512": "sha512-LOLDCp2RcmjUW6oqeSrlzLqSyB07gjTuLZinWL3jBFqPj8kQxAL0DXS0ZLKegGx5IM78FXlJctNYY4jqFxHT+w==", "sources": ["https://api.nuget.org/v3/index.json"], "dependencies": {"net10.0": ["TruePath"], "net11": [], "net20": [], "net30": [], "net35": [], "net40": [], "net403": [], "net45": [], "net451": [], "net452": [], "net46": [], "net461": ["TruePath"], "net462": ["TruePath"], "net47": ["TruePath"], "net471": ["TruePath"], "net472": ["TruePath"], "net48": ["TruePath"], "net5.0": ["TruePath"], "net6.0": ["TruePath"], "net7.0": ["TruePath"], "net8.0": ["TruePath"], "net9.0": ["TruePath"], "netcoreapp1.0": [], "netcoreapp1.1": [], "netcoreapp2.0": ["TruePath"], "netcoreapp2.1": ["TruePath"], "netcoreapp2.2": ["TruePath"], "netcoreapp3.0": ["TruePath"], "netcoreapp3.1": ["TruePath"], "netstandard": [], "netstandard1.0": [], "netstandard1.1": [], "netstandard1.2": [], "netstandard1.3": [], "netstandard1.4": [], "netstandard1.5": [], "netstandard1.6": [], "netstandard2.0": ["TruePath"], "netstandard2.1": ["TruePath"]}, "targeting_pack_overrides": [], "framework_list": [], "tools": {}},
        ],
    )
